service:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://postgres:callabangapaupau@db:5432/messenger_db
    depends_on:
      db:
        condition: servec_healthy

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=callabangapaupau
      - POSTGRES_DB=messenger_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_instready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pg_data:      