#!/bin/bash
# LaBerry Security Setup Script for laberry.ru
# This script helps configure LaBerry with maximum security

set -e

echo "🔐 LaBerry Security Setup Wizard"
echo "================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check prerequisites
check_prerequisites() {
    echo "Checking prerequisites..."
    
    if ! command -v openssl &> /dev/null; then
        echo -e "${RED}✗ OpenSSL not found${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ OpenSSL${NC}"
    
    if ! command -v sqlite3 &> /dev/null; then
        echo -e "${YELLOW}⚠ SQLite3 not found (optional)${NC}"
    else
        echo -e "${GREEN}✓ SQLite3${NC}"
    fi
}

# Generate SECRET_KEY
generate_secret_key() {
    echo ""
    echo "Generating SECRET_KEY for JWT signing..."
    SECRET_KEY=$(openssl rand -base64 48 | tr -d '\n' | tr '+/' '_-')
    echo -e "${GREEN}✓ SECRET_KEY generated${NC}"
    echo "Length: ${#SECRET_KEY} characters"
}

# Create .env file
create_env_file() {
    echo ""
    echo "Creating .env file..."
    
    cat > .env << EOF
# Generated by LaBerry Security Setup
# $(date)

# ============================================
# 🔑 CORE SECURITY
# ============================================
SECRET_KEY=$SECRET_KEY
JWT_ISSUER=laberry

# ============================================
# 🔐 HTTPS/TLS (optional for native TLS)
# ============================================
# For use with reverse proxy, leave these commented:
# LB_TLS_CERT_PATH=/path/to/cert.pem
# LB_TLS_KEY_PATH=/path/to/key.pem

LB_DOMAIN=laberry.ru

# ============================================
# 📡 SERVER BINDING
# ============================================
LB_HOST=127.0.0.1
LB_PORT=5000

# ============================================
# 🗄️ DATABASE
# ============================================
DATABASE_URL=sqlite:./laberry.db

# ============================================
# 🛡️ ADMIN PANEL
# ============================================
LB_ENABLE_ADMIN_PANEL=true
LB_ADMIN_HOST=127.0.0.1
LB_ADMIN_PORT=5002
LB_ADMIN_PASSWORD=$(openssl rand -base64 16)

# ============================================
# 📞 VOICE/VIDEO (TURN)
# ============================================
LB_STUN_URLS=stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302

# ============================================
# 🔔 LOGGING
# ============================================
RUST_LOG=info
EOF
    
    echo -e "${GREEN}✓ .env file created${NC}"
    echo "Location: .env"
}

# Create nginx configuration
create_nginx_config() {
    echo ""
    echo "Creating nginx configuration..."
    
    cat > laberry-nginx.conf << 'EOF'
# LaBerry HTTPS Configuration for laberry.ru
# Copy to /etc/nginx/sites-available/laberry.ru
# Then: sudo ln -s /etc/nginx/sites-available/laberry.ru /etc/nginx/sites-enabled/

upstream laberry_backend {
    server 127.0.0.1:5000;
    keepalive 32;
}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name laberry.ru www.laberry.ru;
    return 301 https://$server_name$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name laberry.ru www.laberry.ru;

    # SSL Configuration (Update paths for your certificates)
    ssl_certificate /etc/letsencrypt/live/laberry.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/laberry.ru/privkey.pem;

    # Strong SSL Configuration
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "geolocation=(), microphone=(self), camera=()" always;
    add_header Content-Security-Policy "default-src 'self' https://laberry.ru; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' wss://laberry.ru; object-src 'none'; frame-ancestors 'none'" always;

    # Logging
    access_log /var/log/nginx/laberry-access.log;
    error_log /var/log/nginx/laberry-error.log;

    # Proxy Configuration
    location / {
        proxy_pass http://laberry_backend;
        proxy_http_version 1.1;
        
        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $server_name;
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Rate limiting for auth endpoints
    limit_req_zone $binary_remote_addr zone=auth:10m rate=12r/m;
    
    location /api/auth/ {
        limit_req zone=auth burst=3 nodelay;
        proxy_pass http://laberry_backend;
    }

    # Health check endpoint
    location /health {
        proxy_pass http://laberry_backend;
        access_log off;
    }
}
EOF
    
    echo -e "${GREEN}✓ Nginx configuration created${NC}"
    echo "Location: laberry-nginx.conf"
    echo ""
    echo "To install:"
    echo "  sudo cp laberry-nginx.conf /etc/nginx/sites-available/laberry.ru"
    echo "  sudo ln -s /etc/nginx/sites-available/laberry.ru /etc/nginx/sites-enabled/"
    echo "  sudo nginx -t"
    echo "  sudo systemctl reload nginx"
}

# Create systemd service
create_systemd_service() {
    echo ""
    echo "Creating systemd service configuration..."
    
    cat > laberry.service << EOF
[Unit]
Description=LaBerry Server (E2EE Chat)
After=network.target

[Service]
Type=simple
User=laberry
WorkingDirectory=/opt/laberry
Environment="RUST_LOG=info"
EnvironmentFile=/opt/laberry/.env
ExecStart=/opt/laberry/target/release/laberry_server_bin
Restart=on-failure
RestartSec=10

# Security
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=/opt/laberry

[Install]
WantedBy=multi-user.target
EOF
    
    echo -e "${GREEN}✓ Systemd service configuration created${NC}"
    echo "Location: laberry.service"
    echo ""
    echo "To install:"
    echo "  sudo cp laberry.service /etc/systemd/system/"
    echo "  sudo systemctl daemon-reload"
    echo "  sudo systemctl enable laberry"
    echo "  sudo systemctl start laberry"
}

# Show summary
show_summary() {
    echo ""
    echo "================================"
    echo -e "${GREEN}✅ Setup Complete!${NC}"
    echo "================================"
    echo ""
    echo "Files created:"
    echo "  • .env (with SECRET_KEY)"
    echo "  • laberry-nginx.conf"
    echo "  • laberry.service"
    echo ""
    echo "Next steps:"
    echo "  1. Obtain SSL certificate:"
    echo "     certbot certonly --standalone -d laberry.ru"
    echo ""
    echo "  2. Install and test nginx:"
    echo "     sudo cp laberry-nginx.conf /etc/nginx/sites-available/laberry.ru"
    echo "     sudo nginx -t"
    echo ""
    echo "  3. Install systemd service:"
    echo "     sudo cp laberry.service /etc/systemd/system/"
    echo "     sudo systemctl enable laberry"
    echo ""
    echo "  4. Build and start LaBerry:"
    echo "     cargo build --release"
    echo "     sudo systemctl start laberry"
    echo ""
    echo "  5. Verify:"
    echo "     curl -I https://laberry.ru"
    echo ""
    echo -e "${YELLOW}⚠️  Important:${NC}"
    echo "  • Keep .env file secure (contains SECRET_KEY)"
    echo "  • Review nginx config for your environment"
    echo "  • Ensure SSL certificates auto-renew"
    echo "  • Monitor logs: tail -f /var/log/nginx/laberry-*.log"
    echo ""
}

# Main execution
main() {
    check_prerequisites
    generate_secret_key
    create_env_file
    create_nginx_config
    create_systemd_service
    show_summary
}

main "$@"
