services:
  coturn:
    image: coturn/coturn:latest
    container_name: laberry-turn
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    environment:
      - DETECT_EXTERNAL_IP=yes
