listening-port=3478
tls-listening-port=5349

fingerprint
lt-cred-mech
use-auth-secret

realm=laberry
server-name=laberry-turn

static-auth-secret=CHANGE_ME_32PLUS_CHARS

min-port=49160
max-port=49200

no-multicast-peers
no-cli
